spring:
  application:
    name: course-service

  datasource:
    url: jdbc:mysql://localhost:3307/courseDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    password: "course"
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: false

    hibernate:
      ddl-auto: update

server:
  port: 8082

